<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>DvergrAllies</AssemblyName>
    <Description>A Valheim mod that allows taming and crossbreeding Dvergrs.</Description>
    <Version>1.0.3</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />
    <PackageReference Include="JotunnLib" Version="2.*" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="assembly_valheim" Publicize="true">
      <HintPath>libs\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_guiutils" Publicize="true">
      <HintPath>libs\assembly_guiutils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils" Publicize="true">
      <HintPath>libs\assembly_utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="gui_framework">
      <HintPath>libs\gui_framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="steamworks.net">
      <HintPath>libs\steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>libs\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

